### ISSUE TITLE
SpringBootContextFactory does not store context

### ISSUE THREAD

**Issue by mgoldver** [bigdullrock/fitnesse-spring#1]
Hi folks,
Great job creating this little utility. While it works great, I found that `SpringBootContextFactory.createSpringContext` while returning the properly created context, doesn't store it in the private static `springContext` property. As a result, `currentSpringContext` method always throws an exception.
Could you please add a line to store the newly created context?
Thanks a lot.

**Comment by charlie-harvey** [comment]
Fixed with the latest commit.

https://github.com/bigdullrock/fitnesse-spring/commit/da5c8c863e2fafdc272ebd94df98be131e2da750

Version 0.2.0 was released to Maven Central.

**Comment by mgoldver** [comment]
You are the man!
Thank you.

Mike G
